name: Release Builder and Publisher

on:
  release:
    types: [prereleased]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js (adjust version if needed)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build the app for release
        run: npm run dist

      - name: Create a temporary directory for release assets
        run: mkdir release_assets

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: |
            find /release/${{ github.ref }} -type f

      - name: Publish the release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Access token with release permissions
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}  # Customize release name if desired
          draft: false  # Publish the release after build and asset upload
