name: Release on Push to Master

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Print package.json version
        run: node -p "require('./package.json').version"

      - name: Create Release
        uses: justincy/github-action-npm-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
