name: Print Package Version

on:
  push:
    branches:
      - master

jobs:
  print-version:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Print package.json version
        run: |
          npm install jq-cli
          echo "Package version: $(jq -r '.version' package.json)"
